name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31.6'

    - name: Download DirectX SDK
      run: |
        curl -L -o dxsdk.exe "https://download.microsoft.com/download/1/1/3/1113D1B1-3B3D-4B5D-8B3D-1B3D1B3D1B3D/dxsdk.exe"
        start /wait dxsdk.exe /S /D=C:\DirectXSDK  # Silent install to a specific directory

    - name: Configure
      run: |
        cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release
